message("System name: ${CMAKE_SYSTEM_NAME}")
message("System version: ${CMAKE_SYSTEM_VERSION}")
message("Toolchain: ${CMAKE_EXTERNAL_TOOLCHAIN}")
message("Prefix: ${CMAKE_PREFIX_PATH}")
message("Sysroot: ${CMAKE_SYSROOT}")
message("Ar: ${CMAKE_AR}")
message("As: ${CMAKE_ASM_COMPILER}")
message("Ld: ${CMAKE_LINKER}")
message("Cc: ${CMAKE_C_COMPILER}")
message("Cc Ar: ${CMAKE_C_COMPILER_AR}")
message("Cc Ranlib: ${CMAKE_C_COMPILER_RANLIB}")
message("Cxx: ${CMAKE_CXX_COMPILER}")
message("Cxx Ar: ${CMAKE_CXX_COMPILER_AR}")
message("Cxx Ranlib: ${CMAKE_CXX_COMPILER_RANLIB}")
message("Ranlib: ${CMAKE_RANLIB}")
